name: trigger-book-build
on:
  pull_request:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files in repo
        uses: actions/checkout@main
      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: "openradar"
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: "ghcr.io"
          PUBLIC_REGISTRY_CHECK: true
          APPENDIX_FILE: "binder/appendix.txt"
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: cookbook-dev
      artifact_name: book-zip-${{ github.event.number }}
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
